### ISSUE TITLE
Y.observeTypeCreated is not a function

### ISSUE THREAD

**Issue by getflourish** [YousefED/reactive-crdt#10]
I’ve been trying to move my test code to a CodeSandbox. The code works fine with Vite on my local machine, but somehow I see an error when I tried to replicate it on CodeSandbox. No idea what’s wrong and wether it is related to this repo…

https://codesandbox.io/s/mystifying-wood-5zf8z?file=/src/App.vue

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/183989/118450838-e7abbf00-b6f4-11eb-85fc-34343adf767b.png">

**Comment by YousefED** [comment]
This is an issue I had as well with CodeSandbox. CodeSandbox doesn't pick up my custom Yjs build correctly (it's loaded [here](https://github.com/YousefED/reactive-crdt/blob/08aaa8a2bc5c1de753ee7fe43e06e82859eb2021/packages/reactive-crdt/package.json#L34).

It should be resolved when my change lands in yjs: https://github.com/yjs/yjs/pull/298

**Comment by YousefED** [comment]
@getflourish this is fixed if you upgrade to the latest version: https://codesandbox.io/s/red-morning-lshps?file=/src/App.vue
