### ISSUE TITLE
Errors with Vue example

### ISSUE THREAD

**Issue by clibu** [YousefED/reactive-crdt#11]
I tried installing the Vue example with npm and it failed - I try not to use npm. Then did `yarn install` and all went well. However when I go `yarn run serve` I get:
````
yarn run v1.22.10
$ vue-cli-service serve
 INFO  Starting development server...
98% after emitting CopyPlugin

 ERROR  Failed to compile with 4 errors                                                                                             6:49:29 pm
This dependency was not found:

* yjs in ./node_modules/@reactivedata/reactive-crdt/dist/reactive-crdt.module.js, ./node_modules/@reactivedata/yjs-reactive-bindings/dist/yjs-reactive-bindings.module.js and 2 others

To install it, you can run: npm install --save yjs
Issues checking in progress...
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
No issues found.
````

I just wanted to have a quick play, so don't go to any trouble. I'm new to yjs and saw your post: https://discuss.yjs.dev/t/reactive-crdt-easy-to-use-api-to-use-yjs-and-build-collaborative-apps/507/7 

I understand you are using a fork of yjs.

FYI For managing state I was using NX Observe, then moved to [onChange](https://www.npmjs.com/package/on-change) and more recently the reactive code in [Acebase](https://github.com/appy-one/acebase) which is the best fit so far. 

I am now looking seriously at yjs which is how I discovered your lib. The ability to use plain JS objects and arrays is very appealing. I don't use Vue or React 😀

PS. I'm using Node v16.1.0 on Windows 10

**Comment by clibu** [comment]
I've tried creating a new project with the https://github.com/YousefED/reactive-crdt#without-framework example and am running into problems with your reactive-crdt.js etc. files using `require()` but the example code uses es6 import's. I'm not using webpack, babel etc. and just running the example in Node.

**Comment by YousefED** [comment]
Hi @clibu ! Nice to see you're looking into reactive-crdt. If you could share some example code, I can look into your issue!

**Comment by clibu** [comment]
@YousefED If you try:
````
> yarn install
> cd to todo-vue
> yarn install
> yarn run serve
````
and see if it works for you.

**Comment by YousefED** [comment]
Hi @clibu ,

Do you have the same issue with npm instead of yarn? For me it works with NPM

(I'm running into another compatibility issue with Vue though, which I'm solving separately)

**Comment by YousefED** [comment]
@clibu I expect this is resolved in the latest version
