### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by kappa90** [YousefED/reactive-crdt#13]
Hi, trying to install the library, I get a dependency failure due to an apparent incompatibility with yjs

```
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! yjs@13.5.5 dist: `rm -rf dist && rollup -c && tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the yjs@13.5.5 dist script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by YousefED** [comment]
Hi!

Thanks for reporting, two questions:
- what nodejs / npm versions are you using, and which OS?
- Do you have a different dependency on yjs in your project?

**Comment by marsch** [comment]
actually i do experience issues as well, why are you using the patched version of `yjs`? is there a reason for this?

**Comment by YousefED** [comment]
@marsch yes, this is described here: https://github.com/yjs/yjs/pull/298. I hope this gets merged soon to make using reactive-crdt more straightforward

**Comment by YousefED** [comment]
This should be solved in the latest version. We still depend on a yjs fork untill https://github.com/yjs/yjs/pull/298 is merged, but the installation issue should be resolved
